name: mixcosechas_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  cloud_firestore: null
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: null
  firebase_core: null
  firebase_database: null
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.7.0
  get: null
  provider: ^6.0.5
  quickalert: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/admin.png
    - assets/images/agricultor.png
    - assets/images/analista.png
    - assets/images/logo_MIXCOSECHAS.png
    - assets/images/simple_logo_MIXCOSECHAS.png
    - assets/images/hover.png
    - assets/images/hoverTry.png
    - assets/images/rendimiento.png
    - assets/images/ahorro.png
    - assets/images/cronometro.png
    - assets/images/organico.png
    - assets/departamentos_Municipios.csv
    - assets/images/_MIXCOSECHAS.png

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-VariableFont_wdth,wght.ttf
