// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVJ1TN1z5yFpsfOOejR4rbZoZxQQHoPI',
    appId: '1:667116282708:web:2945721f4e0351ff8e5ec1',
    messagingSenderId: '667116282708',
    projectId: 'mixcosechas',
    authDomain: 'mixcosechas.firebaseapp.com',
    storageBucket: 'mixcosechas.appspot.com',
    measurementId: 'G-4WRJP148SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnx3NhBvV1vT3AUw-z-8dcgzZlKMDt9c',
    appId: '1:667116282708:android:ac1860fcea5f18f88e5ec1',
    messagingSenderId: '667116282708',
    projectId: 'mixcosechas',
    storageBucket: 'mixcosechas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hJNlXvgZiVHWHOI-Juhp84J5cFa1FrU',
    appId: '1:667116282708:ios:576e710053432eba8e5ec1',
    messagingSenderId: '667116282708',
    projectId: 'mixcosechas',
    storageBucket: 'mixcosechas.appspot.com',
    iosClientId: '667116282708-tppg2e58i1l2mp3829nnqq53t66u98ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.mixcosechasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4hJNlXvgZiVHWHOI-Juhp84J5cFa1FrU',
    appId: '1:667116282708:ios:a04a923942af4a4b8e5ec1',
    messagingSenderId: '667116282708',
    projectId: 'mixcosechas',
    storageBucket: 'mixcosechas.appspot.com',
    iosClientId: '667116282708-j1jvb884nn9oih83o285i52968orm6jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mixcosechasApp.RunnerTests',
  );
}
